// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnlzMPWpRUfOa7OR0l3g2oifnqL42DU_k',
    appId: '1:952358232816:android:c05958560122cd113b5835',
    messagingSenderId: '952358232816',
    projectId: 'login-4819a',
    storageBucket: 'login-4819a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdGUDOGtU-YT28KoMChp2M48jgdc13_c',
    appId: '1:952358232816:ios:66e64f815cf3de773b5835',
    messagingSenderId: '952358232816',
    projectId: 'login-4819a',
    storageBucket: 'login-4819a.appspot.com',
    androidClientId: '952358232816-1gjisni2idifi62158lokb2b0jm2cb02.apps.googleusercontent.com',
    iosClientId: '952358232816-a0vqf8uja3fi2bcpl8ibbjh2dfq454hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

}